### ISSUE TITLE
No longer launches on second launch

### ISSUE THREAD

**Issue by ErATOme51** [diogomartino/palworld-ds-gui#1]
When the server is configured for the first time, everything works fine. 

If you close the GUI, and open it again, it blocks on initializing, please wait.

![Capture d'écran 2024-01-30 180852](https://github.com/diogomartino/palworld-ds-gui/assets/105929634/235ca5f2-7681-4418-a8b2-e454c48d3345)

Thanks for this great project!

**Comment by diogomartino** [comment]
Hi, I might have an idea of whats happening there but I'm not sure. I'll release a new version today to see if I can fix it blindly and improve the logging of errors so I can be sure what's going on. I'll ping you here once I release it so you can try it. Thanks for the feedback 👍

**Comment by diogomartino** [comment]
@ErATOme51 done. If you could try the new version I would appreciate. Just delete the old executable and drop the new one. In case it still gets stuck, paste here the `logs.txt` content
