### ISSUE TITLE
Keep stored parameters

### ISSUE THREAD

**Issue by BoringMan314** [diogomartino/palworld-ds-gui#10]
The default parameter setting is
-useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
I want to add -EpicApp=PalServer
So I changed it to
-useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -EpicApp=PalServer
But it will not be remembered next time you start it.
Or am I setting it in the wrong place?

**Comment by diogomartino** [comment]
Hey! Those launch params should be saved once you start the server. Are you saying you change the params, start the server and when you close the app and open it again they did not save?

**Comment by BoringMan314** [comment]
Fixed after restarting computer
