### ISSUE TITLE
VPS Server transfer to GUI.

### ISSUE THREAD

**Issue by mrdumma** [diogomartino/palworld-ds-gui#11]
Is there anyway i can transfer my current dedicated server to use this GUI? I just didn't want my server to be deleted during the transition.  Does the game save all data on IP or VPS storage.  

Thanks again for this!

The video i use as reference to host my server on VPS
https://www.youtube.com/watch?v=thn0wDE5LDg

**Comment by diogomartino** [comment]
If you mean having the GUI in the windows VPS yes, you can. You just need to move the server folder (the one that has `PalServer.exe`, in the case of that tutorial is the `steamapps/common/PalServer`) to the same folder of the GUI executable. Your server folder needs to be named exactly `server` or it won't work. You should have a structure like this:

![image](https://github.com/diogomartino/palworld-ds-gui/assets/16502356/296eb8b9-f9a4-42ec-8859-a5b203f1793b)

Now just open the GUI and everything should work.

**Comment by diogomartino** [comment]
This has changed with the new versions. Please read [https://github.com/diogomartino/palworld-ds-gui/blob/main/HOW_TO_USE.md#using-an-existing-server](https://github.com/diogomartino/palworld-ds-gui/blob/main/HOW_TO_USE.md#using-an-existing-server)
