### ISSUE TITLE
Admin doesn't work

### ISSUE THREAD

**Issue by ISOCASSELGenMi** [diogomartino/palworld-ds-gui#12]
Couldn't connect to the server and just keep connecting.
![image](https://github.com/diogomartino/palworld-ds-gui/assets/67268851/091084f5-cea5-43cf-9c7a-2258ce900e5e)

**Comment by BoringMan314** [comment]
I also encountered the same problem

**Comment by diogomartino** [comment]
I can't reproduce that. The only thing I found is that RCON only works after you start the server for the first time, join and spawn in the world. Then you restart the server and it starts working. But that's how their server works, nothing I can do about it apart from warning the users somehow.

Assuming you have already enabled RCON in the settings, if you do this steps and it still doesn't work, it might be something network related, I don't know...

**Comment by ISOCASSELGenMi** [comment]
Update my situation.
I can type the system massage to the server but just couldn't see any online player
quite weird. maybe the problem is on steam api or sth?
![image](https://github.com/diogomartino/palworld-ds-gui/assets/67268851/0e79cf74-c888-4647-beb0-31234912a201)

**Comment by ISOCASSELGenMi** [comment]
Now it works but I didn't do anything. LOL
Thank you anyway.
