### ISSUE TITLE
(Feature Request Again) it is possible change the backup to minutes from hours

### ISSUE THREAD

**Issue by Mpiffer** [diogomartino/palworld-ds-gui#15]
Backups from gui is such a angel in this bugged game, but i have a new issue, i`m providing hosting in my local. today i just run out of power and the server just reset. i used a backup, but 46 minutes before,but much progress has lost. can be insteresting make a backup like 5 on 5 or 10 on 10 minutes. 

Other thing is the possibility to manage mods and more from the GUI, like install UE4SS and more, The mods increasing much the game time. 

Thanks for do the other request, and btw such a great job, TY <3.

**Comment by diogomartino** [comment]
Yea, losing progress is always a pain... I'll change that in the next version so you can go lower than 1 hour. Regarding the mods, I never really modded the game yet but I can explore that, I think having a easy way of listing and installing mods with 1 click would be great! Thanks for the feedback, will definitely check it out 👍

**Comment by diogomartino** [comment]
@Mpiffer sorry for the long wait. Just finished implementing this and I will release it today or tomorrow.
