### ISSUE TITLE
Update server button giving wrong error

### ISSUE THREAD

**Issue by jusitnboggs** [diogomartino/palworld-ds-gui#19]
I get this one clicking on Update Server from the main tab.
![image](https://github.com/diogomartino/palworld-ds-gui/assets/2986451/dc6b8588-a753-476b-b42a-6a0e1a1cf1ee)

I just installed Version V1.0.1 Using both new files. 
![image](https://github.com/diogomartino/palworld-ds-gui/assets/2986451/89fc35e7-3f23-45fa-86c2-f2c32732b2af)

**Comment by diogomartino** [comment]
Do all the other features work correctly? Or none of it works?

**Comment by diogomartino** [comment]
Nevermind, just noticed what's happening. Thanks for the report!
