### ISSUE TITLE
[Feature Request] Use for other server

### ISSUE THREAD

**Issue by WindedHero** [diogomartino/palworld-ds-gui#2]
This tool would be great if it could be used as a client for existing dedicated server setups. 

I was a bit disappointed when it started downloading the server software during first startup.

**Comment by diogomartino** [comment]
If you mean that you would be able to control the server remotely, I think that's kinda of a good idea. Not sure how soon I could do that since that would require a lot of restructuring... I'll think about it, thanks!

**Comment by n3rddoom** [comment]
> This tool would be great if it could be used as a client for existing dedicated server setups.
> 
> I was a bit disappointed when it started downloading the server software during first startup.

I agree with this. It would be really great to use this for an existing server I already made.

**Comment by stephanepapin** [comment]
> > This tool would be great if it could be used as a client for existing dedicated server setups.
> > I was a bit disappointed when it started downloading the server software during first startup.
> 
> I agree with this. It would be really great to use this for an existing server I already made.

+1 because I've existing server :)
