### ISSUE TITLE
[Feature Request]Timed restart and Chinese translation

### ISSUE THREAD

**Issue by lodest-game** [diogomartino/palworld-ds-gui#21]
Resolve memory usage issues.
At least, the configuration interface is introduced in Chinese, pls

**Comment by lodest-game** [comment]
What I mean is to fix the problem of excessive server memory usage by periodically restarting the server.
You know, when the server runs too long, the memory usage is horrible and the lag is extremely severe.
For now, the best way I know of to fix the lag is to restart the server.
Sorry, your reply email was thrown into the trash can by outlook, and I just saw the message today.

**Comment by diogomartino** [comment]
Didn't know that was a problem, but if it is it's a nice feature to have. Thanks!

**Comment by diogomartino** [comment]
Timed restart implemented, translations will be tracked #24.
