### ISSUE TITLE
Can add EpicApp=PalServer Launch option or a space to set the launch options?

### ISSUE THREAD

**Issue by Mpiffer** [diogomartino/palworld-ds-gui#3]
To open a public server need some launch options like.
EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -publiclobby

**Comment by BoringMan314** [comment]
same request

**Comment by diogomartino** [comment]
Sure, I'll add a quick way of adding launch params. Thanks for the feedback!
