### ISSUE TITLE
Request Auto open server

### ISSUE THREAD

**Issue by bate1156** [diogomartino/palworld-ds-gui#31]
Can add? Automatically open the server when the server is crash.

**Comment by diogomartino** [comment]
Sure, I'll add it to my TODO list. Thanks for the feedback!

**Comment by bate1156** [comment]
Thanks brother, I still have one more thing to offer, which is to add a box to type the rcon command.

**Comment by diogomartino** [comment]
Implemented both features, a new version will be released soon. Thanks for the suggestions!

**Comment by bate1156** [comment]
I have tested it in the new version. It works great and has no issues. Thank you very much, brother.
