### ISSUE TITLE
GUI disconnecting

### ISSUE THREAD

**Issue by rkirman** [diogomartino/palworld-ds-gui#34]
On occasion my GUI disconnects itself, it happens either on the server machine or another machine on the network, once it happens I can't reconnect either GUI or web, both are set up and work fine normally, I get this message in the server command window
"write tcp 127.0.0.1:21577->127.0.0.1:53848: wsasend: An existing connection was forcibly closed by the remote host."
the only way to fix this is to close the command windows, (both winserver and palworld server) and restart winserver, once done i am able to open GUI and restart the server.

**Comment by diogomartino** [comment]
Does that happen when the app is open for some time? Also, are you using the windows app or the web interface?

**Comment by rkirman** [comment]
typically in the windows app and yeah most of the time the app is left open constantly, but i have had it fail just after opening the app, typically i try the web interface after the app fails

**Comment by diogomartino** [comment]
Feel free to open it when you have more info
