### ISSUE TITLE
[CONTACT] Not an issue it's a contact attempt xD

### ISSUE THREAD

**Issue by thejcpalma** [diogomartino/palworld-ds-gui#38]
Your contact info on your profile seems to not be working and wanted to have a chat with you about your project and one i'm maintaining.
Add me on discord it's the same username: thejcpalma
My project is: [Palworld Dedicated Server Docker](https://github.com/thejcpalma/palworld-dedicated-server-docker)

**Comment by diogomartino** [comment]
Yea, it's probably not working, I need to check that. Added you on discord :)
