### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by stephanepapin** [diogomartino/palworld-ds-gui#9]
Hi 
Sheduled stop/start with ingame messages (up to 5 with timers configurable) + Discord whebook for stop/start
Regards

**Comment by diogomartino** [comment]
Hey! The scheduled stop/start you mean having a way of picking an hour of the day where the server will automatically turn on and another when it turns it off? Looks like a good idea to me. The discord webhook should also be fairly easy to implement in the future once I finish the restructuring for supporting remote servers. But not sure what you meat when you talked about in game messages and 5 timers.

**Comment by diogomartino** [comment]
Timed restarts implemented in the new version. Discord webhooks will be tracked in #25.
